steps:
  # Шаг 1: Сборка основного Docker-образа
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/satvabot:$BUILD_ID', '.']

  # Шаг 2: Отправка образа в Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/satvabot:$BUILD_ID']

  # Шаг 3: Развертывание образа в Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'satvabot'
      - '--image=gcr.io/$PROJECT_ID/satvabot:$BUILD_ID'
      - '--region=asia-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-secrets=BOT_TOKEN=BOT_TOKEN:latest,ADMINS=ADMINS:latest'
      - '--set-env-vars=APP_URL=https://satvabot-4zxzz3i35q-de.a.run.app'
images:
  - 'gcr.io/$PROJECT_ID/satvabot:$BUILD_ID'
